name: build-go-binary

on:
  release:
    types: [created, edited]

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - goarch: amd64
          goos: linux
        - goarch: amd64
          goos: darwin
        - goarch: arm64
          goos: linux
        - goarch: arm64
          goos: darwin
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with: 
          go-version: 1.20.0
      - name: Making Go Version Manager
        run: make build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - name: Uploading assets...
        if: ${{ !env.ACT }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./gvm_${{ matrix.goos }}_${{ matrix.goarch }}
          asset_name: gvm_${{ matrix.goos }}_${{ matrix.goarch }}

